name: henshin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  image_cropper_for_web: 6.0.2
  provider: ^6.1.2
  go_router: ^14.2.1



  firebase_storage: ^12.3.4

  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  intl: 0.19.0
#  json_path: ^0.3.1
  page_transition: ^2.0.4
  timeago: ^3.1.0
  url_launcher: ^6.0.17

  # firebase
  firebase_core: ^3.6.0
  firebase_core_web: ^2.8.0
  firebase_auth: ^5.3.1
  firebase_auth_web: ^5.8.1
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4

  # cupertino
  cupertino_icons: ^1.0.4
  logger: ^2.4.0

  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.1
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_launcher_icon.png
